import { spawn, ChildProcess } from 'child_process';
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { FileManager } from '../files/fileManager';
import { readProjectKeyCache } from '../config/globalConfig';

/**
 * Writes `.capy/next-env.js`, a CommonJS module mapping each decrypted env var
 * name to a `process.env[KEY]` reference. Users import it in next.config.js:
 *
 *   const capyEnv = require('./.capy/next-env');
 *   module.exports = { env: capyEnv };
 *
 * At `next build` time Next.js inlines each value as a string literal into the
 * compiled bundle, so the secrets are available in Edge, Node, or any runtime
 * without needing Capy at runtime.
 */
function emitNextEnvModule(keys: string[]): void {
  const capyDir = join(process.cwd(), '.capy');
  mkdirSync(capyDir, { recursive: true });

  const body = keys
    .map((k) => `  ${JSON.stringify(k)}: process.env[${JSON.stringify(k)}]`)
    .join(',\n');

  const content =
    `// Auto-generated by capy run. Do not edit.\n` +
    `module.exports = {\n${body}\n};\n`;

  writeFileSync(join(capyDir, 'next-env.js'), content, 'utf-8');
}

/**
 * Spawns the child process with the provided environment, forwards signals,
 * and resolves with its exit code. Shared between local and deployed modes.
 */
function spawnChild(args: string[], env: Record<string, string | undefined>): Promise<number> {
  let child: ChildProcess | null = null;
  for (const sig of ['SIGTERM', 'SIGINT', 'SIGHUP'] as const) {
    process.on(sig, () => child?.kill(sig));
  }

  child = spawn(args[0], args.slice(1), {
    env: env as Record<string, string>,
    stdio: 'inherit',
  });

  return new Promise((resolve) => {
    child!.on('error', (err) => {
      console.error(`capy run: ${err.message}`);
      resolve(1);
    });
    child!.on('close', (code) => resolve(code ?? 1));
  });
}

export async function runCommand(args: string[]): Promise<number> {
  if (args.length === 0) {
    console.error('Usage: capy run -- <command> [args...]');
    return 1;
  }

  const secretsBlob = process.env.SECRETS_BLOB;
  const projectKey = process.env.PROJECT_KEY;

  // Guard: both or neither. Half-configured deploys fail loudly instead of
  // silently falling back to local mode and picking up wrong secrets.
  if ((secretsBlob && !projectKey) || (!secretsBlob && projectKey)) {
    console.error(
      'capy run: SECRETS_BLOB and PROJECT_KEY must both be set, or neither. ' +
        'Got only one — refusing to guess which mode you meant.',
    );
    return 1;
  }

  // Deployed mode: CI, serverless, Vercel builds, etc.
  if (secretsBlob && projectKey) {
    const { parseSecretsBlob, fetchServiceKey, decryptSecretsBlob } = await import(
      '../crypto/deployRuntime'
    );

    let envMap: Record<string, string>;
    try {
      const { deployId, outerBlob, encryptedVars } = parseSecretsBlob(secretsBlob);
      const apiUrl = process.env.CAPY_API_URL ?? 'https://api.capy.sc';
      console.error('capy run: fetching deploy key...');
      const serviceKey = await fetchServiceKey(
        apiUrl,
        deployId.toString('hex'),
        outerBlob.toString('base64'),
      );
      envMap = decryptSecretsBlob(encryptedVars, projectKey, serviceKey, deployId);
    } catch (err: any) {
      console.error(`capy run: ${err.message}`);
      return 1;
    }

    // Auto-emit .capy/next-env.js for Next.js build-time inlining. Best-effort
    // — failure to write is non-fatal (e.g., read-only FS in exotic envs).
    try {
      emitNextEnvModule(Object.keys(envMap));
    } catch {
      // No-op. next-env.js is a convenience; the child still gets the env.
    }

    // dotenv precedence: pre-existing process.env wins over the decrypted
    // values. Shell overrides stay sovereign.
    const childEnv = { ...envMap, ...process.env };
    return spawnChild(args, childEnv);
  }

  // Local mode: read .env from CWD, decrypt capy: values with the project key
  // resolved from CAPY_KEY env var, then the per-project cache written by the
  // last successful `capy sync`.
  const fm = new FileManager();
  const envFromFile = fm.readEnvFile();

  // Merge: .env values are only injected where process.env doesn't already set
  // them. Shell overrides win (dotenv precedence, same as deployed mode).
  const env: Record<string, string | undefined> = { ...envFromFile, ...process.env };

  // Find capy: prefixed values that need decryption.
  const toDecrypt: Array<[string, string]> = [];
  for (const [k, v] of Object.entries(env)) {
    if (typeof v === 'string' && fm.isEncrypted(v)) {
      toDecrypt.push([k, v]);
    }
  }

  if (toDecrypt.length === 0) {
    // Pure plaintext .env — no key required.
    return spawnChild(args, env);
  }

  // Resolve the project key.
  let projectKeyHex: string | undefined = process.env.CAPY_KEY;
  if (projectKeyHex && !/^[0-9a-f]{64}$/.test(projectKeyHex)) {
    console.error('capy run: CAPY_KEY must be a 64-character hex string (32-byte key).');
    return 1;
  }

  if (!projectKeyHex) {
    // Try the per-project cache populated by `capy sync`. Needs org_id +
    // project_id, which live in keep.lock at the project root.
    const keepPath = join(process.cwd(), 'keep.lock');
    if (existsSync(keepPath)) {
      try {
        const keep = JSON.parse(readFileSync(keepPath, 'utf-8'));
        if (keep?.org_id && keep?.project_id) {
          const cached = readProjectKeyCache(keep.org_id, keep.project_id);
          if (cached) projectKeyHex = cached;
        }
      } catch {
        // keep.lock malformed — fall through to missing-key error.
      }
    }
  }

  if (!projectKeyHex) {
    console.error(
      'capy run: no decryption key available. Run `capy` to sync this project, ' +
        'or set CAPY_KEY to a 64-character hex project key.',
    );
    return 1;
  }

  // Decrypt into a buffer first so we never partially mutate env.
  const decrypted: Array<[string, string]> = [];
  for (const [k, v] of toDecrypt) {
    try {
      decrypted.push([k, fm.decryptValue(v, projectKeyHex)]);
    } catch (err: any) {
      console.error(`capy run: failed to decrypt "${k}": ${err.message}`);
      return 1;
    }
  }

  for (const [k, v] of decrypted) env[k] = v;
  return spawnChild(args, env);
}
