import { spawn, ChildProcess } from 'child_process';
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { FileManager } from '../files/fileManager';

/**
 * Writes `.capy/next-env.js`, a CommonJS module mapping each decrypted env var
 * name to a `process.env[KEY]` reference. Users import it in next.config.js:
 *
 *   const capyEnv = require('./.capy/next-env');
 *   module.exports = { env: capyEnv };
 *
 * At `next build` time Next.js inlines each value as a string literal into the
 * compiled bundle, so the secrets are available in Edge, Node, or any runtime
 * without needing Capy at runtime.
 */
function emitNextEnvModule(keys: string[]): void {
  const capyDir = join(process.cwd(), '.capy');
  mkdirSync(capyDir, { recursive: true });

  const body = keys
    .map((k) => `  ${JSON.stringify(k)}: process.env[${JSON.stringify(k)}]`)
    .join(',\n');

  const content =
    `// Auto-generated by capy run. Do not edit.\n` +
    `module.exports = {\n${body}\n};\n`;

  writeFileSync(join(capyDir, 'next-env.js'), content, 'utf-8');
}

/**
 * Spawns the child process with the provided environment, forwards signals,
 * and resolves with its exit code. Shared between local and deployed modes.
 */
function spawnChild(args: string[], env: Record<string, string | undefined>): Promise<number> {
  let child: ChildProcess | null = null;
  for (const sig of ['SIGTERM', 'SIGINT', 'SIGHUP'] as const) {
    process.on(sig, () => child?.kill(sig));
  }

  child = spawn(args[0], args.slice(1), {
    env: env as Record<string, string>,
    stdio: 'inherit',
  });

  return new Promise((resolve) => {
    child!.on('error', (err) => {
      console.error(`capy run: ${err.message}`);
      resolve(1);
    });
    child!.on('close', (code) => resolve(code ?? 1));
  });
}

export async function runCommand(args: string[]): Promise<number> {
  if (args.length === 0) {
    console.error('Usage: capy run -- <command> [args...]');
    return 1;
  }

  const secretsBlob = process.env.SECRETS_BLOB;
  const projectKey = process.env.PROJECT_KEY;

  // Guard: both or neither. Half-configured deploys fail loudly instead of
  // silently falling back to local mode and picking up wrong secrets.
  if ((secretsBlob && !projectKey) || (!secretsBlob && projectKey)) {
    console.error(
      'capy run: SECRETS_BLOB and PROJECT_KEY must both be set, or neither. ' +
        'Got only one — refusing to guess which mode you meant.',
    );
    return 1;
  }

  // Deployed mode: CI, serverless, Vercel builds, etc.
  if (secretsBlob && projectKey) {
    const { parseSecretsBlob, fetchServiceKey, decryptSecretsBlob } = await import(
      '../crypto/deployRuntime'
    );

    let envMap: Record<string, string>;
    try {
      const { deployId, outerBlob, encryptedVars } = parseSecretsBlob(secretsBlob);
      const apiUrl = process.env.CAPY_API_URL ?? 'https://api.capy.sc';
      console.error('capy run: fetching deploy key...');
      const serviceKey = await fetchServiceKey(
        apiUrl,
        deployId.toString('hex'),
        outerBlob.toString('base64'),
      );
      envMap = decryptSecretsBlob(encryptedVars, projectKey, serviceKey, deployId);
    } catch (err: any) {
      console.error(`capy run: ${err.message}`);
      return 1;
    }

    // Auto-emit .capy/next-env.js for Next.js build-time inlining. Best-effort
    // — failure to write is non-fatal (e.g., read-only FS in exotic envs).
    try {
      emitNextEnvModule(Object.keys(envMap));
    } catch {
      // No-op. next-env.js is a convenience; the child still gets the env.
    }

    // dotenv precedence: pre-existing process.env wins over the decrypted
    // values. Shell overrides stay sovereign.
    const childEnv = { ...envMap, ...process.env };
    return spawnChild(args, childEnv);
  }

  // Local mode: read .env from CWD, then resolve the project key via the
  // server's co-decrypt endpoint so every decryption is audit-logged. No
  // local key caching, no CAPY_KEY escape hatch — server must be reachable.
  const fm = new FileManager();
  const envFromFile = fm.readEnvFile();

  // Merge: .env values are only injected where process.env doesn't already set
  // them. Shell overrides win (dotenv precedence, same as deployed mode).
  const env: Record<string, string | undefined> = { ...envFromFile, ...process.env };

  // Find capy: prefixed values that need decryption.
  const toDecrypt: Array<[string, string]> = [];
  for (const [k, v] of Object.entries(env)) {
    if (typeof v === 'string' && fm.isEncrypted(v)) {
      toDecrypt.push([k, v]);
    }
  }

  if (toDecrypt.length === 0) {
    // Pure plaintext .env — no key required.
    return spawnChild(args, env);
  }

  const keepPath = join(process.cwd(), 'keep.lock');
  if (!existsSync(keepPath)) {
    console.error(
      'capy run: no keep.lock in the current directory. Run `capy` here first to sync.',
    );
    return 1;
  }

  let orgId: string | undefined;
  let projectId: string | undefined;
  try {
    const keep = JSON.parse(readFileSync(keepPath, 'utf-8'));
    orgId = keep?.org_id;
    projectId = keep?.project_id;
  } catch {
    console.error('capy run: keep.lock is malformed. Run `capy` to re-sync.');
    return 1;
  }
  if (!orgId || !projectId) {
    console.error('capy run: keep.lock missing org_id/project_id. Run `capy` to re-sync.');
    return 1;
  }

  let projectKeyHex: string;
  try {
    const { AuthService } = await import('../auth/authService');
    const { ServiceClient } = await import('../service/serviceClient');
    const { resolveProjectKey } = await import('../crypto/keyResolver');

    const auth = new AuthService();
    const result = await auth.authenticateSilent(orgId);
    if (!result.success || !result.user_id) {
      console.error('capy run: not authenticated. Run `capy` to sign in.');
      return 1;
    }

    const svc = new ServiceClient();
    svc.setTokenProvider(() => auth.getValidToken());
    const keyServiceOps = {
      coDecrypt: (o: string, c: string) => svc.coDecrypt(o, c).then(r => r.plaintext),
      wrapOuterLayer: (o: string, p: string) => svc.wrapOuterLayer(o, p).then(r => r.ciphertext),
    };

    projectKeyHex = await resolveProjectKey(orgId, projectId, result.user_id, keyServiceOps);
  } catch (err: any) {
    console.error(`capy run: failed to resolve project key: ${err.message}`);
    return 1;
  }

  // Decrypt into a buffer first so we never partially mutate env.
  const decrypted: Array<[string, string]> = [];
  for (const [k, v] of toDecrypt) {
    try {
      decrypted.push([k, fm.decryptValue(v, projectKeyHex)]);
    } catch (err: any) {
      console.error(`capy run: failed to decrypt "${k}": ${err.message}`);
      return 1;
    }
  }

  for (const [k, v] of decrypted) env[k] = v;
  return spawnChild(args, env);
}
