/**
 * Canonical generator: capy/scripts/sync-init-run-contract.ts.
 * Run here to sync both consumers, or in a standalone CLI/Keep checkout.
 * --check verifies source bytes when available and hashes in standalone CI.
 * Consumer copies of this script, wire types and corpus are generated only.
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const packageName = (JSON.parse(readFileSync(resolve(packageRoot, 'package.json'), 'utf8')) as Readonly<{ name: string }>).name;
const monorepo = [process.env.CAPY_MONOREPO_ROOT, packageRoot, resolve(packageRoot, '../..'), resolve(packageRoot, '..')]
  .find(candidate => candidate !== undefined && existsSync(resolve(candidate, 'service/src/initRuns/contract.ts')));
const consumers = [
  { name: '@capysc/cli', root: 'packages/cli', contract: 'src/auth/initRunContract.ts', manifest: 'src/auth/initRunContract.sources.json' },
  { name: 'keep-app', root: 'keep', contract: 'src/lib/flow/initRunContract.ts', manifest: 'src/lib/flow/initRunContract.sources.json' },
] as const;
const selected = consumers.filter(consumer => consumer.name === packageName || packageRoot === monorepo);
const checking = process.argv.includes('--check');
const sha = (body: string): string => createHash('sha256').update(body).digest('hex');
const generatedHeader = '// GENERATED by scripts/sync-init-run-contract.ts; do not edit.\n';
const corpusPath = 'tests/fixtures/initRunContract.corpus.json';
const scriptPath = 'scripts/sync-init-run-contract.ts';
type Manifest = Readonly<{ v: 1; files: readonly Readonly<{ output: string; source: string; sha256: string }>[] }>;

if (selected.length === 0) throw new Error('Run the init-run contract sync from its canonical or generated script.');
if (!checking && !monorepo) throw new Error('Init-run source is unavailable; set CAPY_MONOREPO_ROOT to sync.');

for (const consumer of selected) {
  const target = packageName === consumer.name ? packageRoot : resolve(monorepo as string, consumer.root);
  const mapping = [
    { source: 'service/src/initRuns/contract.ts', output: consumer.contract, header: generatedHeader },
    { source: 'service/src/initRuns/contract.corpus.json', output: corpusPath, header: '' },
    { source: scriptPath, output: scriptPath, header: '' },
  ] as const;
  const planned = monorepo ? mapping.map(file => ({
    ...file, body: file.header + readFileSync(resolve(monorepo, file.source), 'utf8'),
  })) : null;
  if (!checking && planned) {
    for (const file of planned) {
      mkdirSync(dirname(resolve(target, file.output)), { recursive: true });
      writeFileSync(resolve(target, file.output), file.body);
    }
    const manifest: Manifest = { v: 1, files: planned.map(file => ({ output: file.output, source: file.source, sha256: sha(file.body) })) };
    writeFileSync(resolve(target, consumer.manifest), JSON.stringify(manifest, null, 2) + '\n');
  }
  const manifest = JSON.parse(readFileSync(resolve(target, consumer.manifest), 'utf8')) as Manifest;
  if (manifest.v !== 1 || manifest.files.length !== mapping.length) throw new Error('Invalid init-run source manifest.');
  for (const file of mapping) {
    const entry = manifest.files.find(item => item.output === file.output && item.source === file.source);
    const body = readFileSync(resolve(target, file.output), 'utf8');
    if (!entry || sha(body) !== entry.sha256) throw new Error(`Generated init-run file changed: ${file.output}`);
    const source = planned?.find(item => item.output === file.output);
    if (source && source.body !== body) throw new Error(`Init-run source drift: ${file.output}`);
  }
  const contract = await import(pathToFileURL(resolve(target, consumer.contract)).href) as Readonly<Record<string, unknown>>;
  const corpus = JSON.parse(readFileSync(resolve(target, corpusPath), 'utf8')) as readonly Readonly<{ name: string; parser: string; valid: boolean; value: unknown }>[];
  for (const item of corpus) {
    const parser = contract[item.parser];
    if (typeof parser !== 'function' || (parser(item.value) !== null) !== item.valid) throw new Error(`Init-run corpus failed: ${item.name}`);
  }
  console.log(`init-run contract: ${consumer.name} ${checking ? 'checked' : 'synced'}; ${corpus.length} wire cases${monorepo ? '' : ' (standalone manifest)'}.`);
}
