// AUTO-GENERATED by scripts/build-screen-assets.mjs. Do not edit by hand.
// Source of truth: packages/fixtures/src/contract.ts (capy monorepo).
// Regenerate with: bun run build:screens (from a monorepo checkout).

/**
 * Data contract between the Capy CLI and the browser screens in `@capysc/ui`.
 *
 * Every screen reads its state exclusively from `window.__CAPY_DATA__`,
 * typed per-screen below. The CLI inlines the payload into the screen's HTML
 * at serve time; the workbench injects fixture payloads through the same
 * mechanism. No client-side fetching for initial render.
 *
 * This file is the single source of truth for screen payload shapes. The CLI
 * repo carries an auto-generated copy (packages/cli/src/ui/screens/contract.ts)
 * regenerated by `bun run build:screens` in packages/cli.
 */

export interface AuthSuccessData {
  /** Seconds before the window tries to close itself. 0 disables auto-close. */
  autoCloseSeconds: number;
}

export interface AuthErrorData {
  /** Display-only failure description. Shown verbatim, never parsed. */
  message: string;
}

export interface ScreenDataMap {
  'auth-success': AuthSuccessData;
  'auth-error': AuthErrorData;
}

export type ScreenName = keyof ScreenDataMap;

export const SCREEN_NAMES: readonly ScreenName[] = ['auth-success', 'auth-error'];
