import { mock, jest, describe, test, expect, beforeEach, afterAll } from 'bun:test';

const mockExistsSync = jest.fn();
const mockReadFileSync = jest.fn();
const mockWriteFileSync = jest.fn();
const mockAppendFileSync = jest.fn();
const mockChmodSync = jest.fn();
const mockMkdirSync = jest.fn();
const mockUnlinkSync = jest.fn();
mock.module('fs', () => ({
  existsSync: mockExistsSync,
  readFileSync: mockReadFileSync,
  writeFileSync: mockWriteFileSync,
  appendFileSync: mockAppendFileSync,
  chmodSync: mockChmodSync,
  mkdirSync: mockMkdirSync,
  unlinkSync: mockUnlinkSync,
}));

afterAll(() => { mock.restore(); });

import { join, dirname } from 'path';
import { FileManager, serializeKeep } from '../../src/files/fileManager';
import { KeepFile, CapyError, ERROR_CODES } from '../../src/types/index';

describe('FileManager', () => {
  let fileManager: FileManager;
  const testRoot = '/test/project';

  beforeEach(() => {
    jest.clearAllMocks();
    fileManager = new FileManager(testRoot);

    // Setup default mock behaviors
    mockExistsSync.mockReturnValue(false);
    mockReadFileSync.mockReturnValue('');
    mockWriteFileSync.mockImplementation(() => {});
    mockAppendFileSync.mockImplementation(() => {});
    mockMkdirSync.mockImplementation(() => {});
    mockUnlinkSync.mockImplementation(() => {});
  });

  describe('readEnvFile', () => {
    test('should read and parse existing .env file', () => {
      const envContent = 'API_KEY=test123\nDB_URL=postgres://localhost';
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(envContent);

      const result = fileManager.readEnvFile();

      expect(result).toEqual({
        API_KEY: 'test123',
        DB_URL: 'postgres://localhost'
      });
      expect(mockReadFileSync).toHaveBeenCalledWith(join(testRoot, '.env'), 'utf-8');
    });

    test('should return empty object for non-existent file', () => {
      mockExistsSync.mockReturnValue(false);

      const result = fileManager.readEnvFile();

      expect(result).toEqual({});
    });

    test('should read from custom path', () => {
      const customPath = '/custom/.env';
      const envContent = 'CUSTOM=value';
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(envContent);

      const result = fileManager.readEnvFile(customPath);

      expect(result).toEqual({ CUSTOM: 'value' });
      expect(mockReadFileSync).toHaveBeenCalledWith(customPath, 'utf-8');
    });

    test('should throw CapyError on read failure', () => {
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockImplementation(() => {
        throw new Error('Permission denied');
      });

      expect(() => fileManager.readEnvFile()).toThrow(CapyError);
      expect(() => fileManager.readEnvFile()).toThrow('Failed to read .env file');
    });
  });

  describe('parseEnvContent', () => {
    test('should parse env content string', () => {
      const content = 'API_KEY=test123\nDB_URL=postgres://localhost\n# Comment\nEMPTY=';

      const result = fileManager.parseEnvContent(content);

      expect(result).toEqual({
        API_KEY: 'test123',
        DB_URL: 'postgres://localhost',
        EMPTY: ''
      });
    });

    test('should handle empty content', () => {
      const result = fileManager.parseEnvContent('');
      expect(result).toEqual({});
    });
  });

  describe('writeKeepFile', () => {
    test('should write keep file with proper formatting', () => {
      const keep: KeepFile = {
        version: '3.0',
        org_id: 'org_123',
        project_id: 'proj_456',
        project_name: 'test-project',
        variables: {}
      };

      mockExistsSync.mockReturnValue(false); // No backup needed

      fileManager.writeKeepFile(keep);

      const expected = {
        _comment: 'Capy lockfile — pins env var identities and value hashes per branch. Safe to commit; no secrets here. Plaintext lives in .env (gitignored). Regenerated by the Capy CLI on sync/push. See https://capy.sc/keep-docs',
        ...keep,
      };
      expect(mockWriteFileSync).toHaveBeenCalledWith(
        join(testRoot, 'keep.lock'),
        JSON.stringify(expected, null, 2) + '\n',
        'utf-8'
      );
    });

    test('should handle write failure with backup restoration', () => {
      const keep: KeepFile = {
        version: '3.0',
        org_id: 'org_123',
        project_id: 'proj_456',
        project_name: 'test-project',
        variables: {}
      };

      const keepPath = join(testRoot, 'keep.lock');
      mockExistsSync.mockImplementation((path) => path === keepPath);
      mockReadFileSync.mockReturnValue('old keep content');

      let writeCallCount = 0;
      mockWriteFileSync.mockImplementation(() => {
        writeCallCount++;
        if (writeCallCount === 2) {
          throw new Error('Write failed');
        }
      });

      expect(() => fileManager.writeKeepFile(keep)).toThrow(CapyError);
    });
  });

  describe('writeKeepFile deterministic output', () => {
    test('should sort variables alphabetically with v3 arrays', () => {
      const keep: KeepFile = {
        version: '3.0',
        org_id: 'org_123',
        project_id: 'proj_456',
        project_name: 'test-project',
        variables: {
          ZEBRA_VAR: [{ resource_id: 'res_z', value_hash: 'hz' }],
          ALPHA_VAR: [{ resource_id: 'res_a', value_hash: 'ha' }, { resource_id: 'res_a', branch: 'staging', value_hash: 'has' }],
          MIDDLE_VAR: [{ resource_id: 'res_m', value_hash: 'hm' }],
        }
      };

      mockExistsSync.mockReturnValue(false);
      fileManager.writeKeepFile(keep);

      const writtenContent = mockWriteFileSync.mock.calls[0][1] as string;
      const parsed = JSON.parse(writtenContent);

      // Variables should be sorted alphabetically
      const varNames = Object.keys(parsed.variables);
      expect(varNames).toEqual(['ALPHA_VAR', 'MIDDLE_VAR', 'ZEBRA_VAR']);

      // v3: arrays of { resource_id, branch?, value_hash }
      expect(parsed.variables.ALPHA_VAR[0].resource_id).toBe('res_a');
      expect(parsed.variables.ALPHA_VAR[0].value_hash).toBe('ha');
      expect(parsed.variables.ALPHA_VAR[1].branch).toBe('staging');
    });

    test('should produce identical output regardless of insertion order', () => {
      const keepA: KeepFile = {
        version: '3.0',
        org_id: 'org_1',
        project_id: 'proj_1',
        project_name: 'test',
        variables: {
          B_VAR: [{ resource_id: 'rb', value_hash: 'hb' }],
          A_VAR: [{ resource_id: 'ra', value_hash: 'ha' }],
        }
      };

      const keepB: KeepFile = {
        version: '3.0',
        org_id: 'org_1',
        project_id: 'proj_1',
        project_name: 'test',
        variables: {
          A_VAR: [{ resource_id: 'ra', value_hash: 'ha' }],
          B_VAR: [{ resource_id: 'rb', value_hash: 'hb' }],
        }
      };

      mockExistsSync.mockReturnValue(false);

      fileManager.writeKeepFile(keepA);
      const outputA = mockWriteFileSync.mock.calls[0][1] as string;

      mockWriteFileSync.mockClear();

      fileManager.writeKeepFile(keepB);
      const outputB = mockWriteFileSync.mock.calls[0][1] as string;

      expect(outputA).toBe(outputB);
    });
  });

  describe('serializeKeep canonical comparison (sync self-heal)', () => {
    // Regression for the bug where a bare `capy` sync rewrote keep.lock on
    // EVERY run — even with an empty .env. During sync, self-heal compares the
    // local keep.lock against the server's keep_file. The local copy is read
    // off disk (so it carries `_comment` and is already sorted); the server's
    // copy has neither. A bare JSON.stringify comparison therefore always saw a
    // difference and rewrote the file. serializeKeep normalizes both sides so
    // the comparison reflects real changes only.

    test('on-disk keep (with _comment) and server keep (without _comment) serialize identically', () => {
      // Shape the server hands back: no _comment, variables in arbitrary order.
      const serverKeep = {
        version: '3.0',
        org_id: 'org_1',
        project_id: 'proj_1',
        project_name: 'test',
        variables: {
          B_VAR: [{ resource_id: 'rb', value_hash: 'hb' }],
          A_VAR: [{ resource_id: 'ra', value_hash: 'ha' }],
        },
      } as KeepFile;

      // Shape on disk: writeKeepFile injects _comment + sorts; readKeepFile
      // returns it verbatim (raw `as KeepFile`), so the parsed object still
      // carries _comment.
      mockExistsSync.mockReturnValue(false);
      fileManager.writeKeepFile(serverKeep);
      const onDiskContent = mockWriteFileSync.mock.calls[0][1] as string;
      const onDiskKeep = JSON.parse(onDiskContent) as KeepFile;
      expect((onDiskKeep as any)._comment).toBeDefined();

      // The fix: self-heal must treat these as equal → no rewrite.
      expect(serializeKeep(onDiskKeep)).toBe(serializeKeep(serverKeep));

      // Documents the root cause: the OLD bare-stringify comparison reported a
      // difference for the very same data, triggering the spurious rewrite.
      expect(JSON.stringify(onDiskKeep)).not.toBe(JSON.stringify(serverKeep));
    });

    test('is independent of variable insertion order and extra entry fields', () => {
      const a = {
        version: '3.0', org_id: 'o', project_id: 'p', project_name: 'n',
        variables: {
          Z: [{ resource_id: 'rz', value_hash: 'hz', connector: { provider: 'aws' } }],
          A: [{ resource_id: 'ra', value_hash: 'ha' }],
        },
      } as unknown as KeepFile;
      const b = {
        version: '3.0', org_id: 'o', project_id: 'p', project_name: 'n',
        variables: {
          A: [{ resource_id: 'ra', value_hash: 'ha' }],
          Z: [{ resource_id: 'rz', connector: { provider: 'aws' }, value_hash: 'hz' }],
        },
      } as unknown as KeepFile;

      expect(serializeKeep(a)).toBe(serializeKeep(b));
    });

    test('reports a real change when a value_hash differs', () => {
      const before = {
        version: '3.0', org_id: 'o', project_id: 'p', project_name: 'n',
        variables: { API_KEY: [{ resource_id: 'r', value_hash: 'old' }] },
      } as KeepFile;
      const after = {
        version: '3.0', org_id: 'o', project_id: 'p', project_name: 'n',
        variables: { API_KEY: [{ resource_id: 'r', value_hash: 'new' }] },
      } as KeepFile;

      expect(serializeKeep(before)).not.toBe(serializeKeep(after));
    });
  });

  describe('writeKeepFile no-op guard', () => {
    const keep: KeepFile = {
      version: '3.0',
      org_id: 'org_1',
      project_id: 'proj_1',
      project_name: 'test',
      variables: {},
    };

    test('does not rewrite keep.lock when on-disk content is already canonical', () => {
      const keepPath = join(testRoot, 'keep.lock');
      mockExistsSync.mockImplementation((p: string) => p === keepPath);
      mockReadFileSync.mockReturnValue(serializeKeep(keep));

      fileManager.writeKeepFile(keep);

      expect(mockWriteFileSync).not.toHaveBeenCalled();
    });

    test('rewrites keep.lock when on-disk content differs', () => {
      const keepPath = join(testRoot, 'keep.lock');
      mockExistsSync.mockImplementation((p: string) => p === keepPath);
      mockReadFileSync.mockReturnValue('stale content');

      fileManager.writeKeepFile(keep);

      expect(mockWriteFileSync).toHaveBeenCalledWith(
        keepPath,
        serializeKeep(keep),
        'utf-8',
      );
    });
  });

  describe('updateGitignore', () => {
    test('should add new entries to .gitignore', () => {
      const entries = ['.env'];
      mockExistsSync.mockReturnValue(false); // No existing .gitignore

      fileManager.updateGitignore(entries);

      expect(mockAppendFileSync).toHaveBeenCalledWith(
        join(testRoot, '.gitignore'),
        '\n# Capy\n',
        'utf-8'
      );
      expect(mockAppendFileSync).toHaveBeenCalledWith(
        join(testRoot, '.gitignore'),
        '.env\n',
        'utf-8'
      );
    });

    test('should not add duplicate entries', () => {
      const entries = ['.env'];
      const existingContent = '.env\nnode_modules\n';

      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(existingContent);

      fileManager.updateGitignore(entries);

      // Should not append anything since entries already exist
      expect(mockAppendFileSync).not.toHaveBeenCalled();
    });

    test('should add only missing entries', () => {
      const entries = ['.env', '.capy/token'];
      const existingContent = '.env\nnode_modules\n';

      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(existingContent);

      fileManager.updateGitignore(entries);

      expect(mockAppendFileSync).toHaveBeenCalledWith(
        join(testRoot, '.gitignore'),
        '\n# Capy\n',
        'utf-8'
      );
      expect(mockAppendFileSync).toHaveBeenCalledWith(
        join(testRoot, '.gitignore'),
        '.capy/token\n',
        'utf-8'
      );
    });

    test('should handle existing .gitignore without trailing newline', () => {
      const entries = ['.env'];
      const existingContent = 'node_modules'; // No trailing newline

      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(existingContent);

      fileManager.updateGitignore(entries);

      expect(mockAppendFileSync).toHaveBeenCalledWith(
        join(testRoot, '.gitignore'),
        '\n',
        'utf-8'
      );
    });

    test('should throw CapyError on write failure', () => {
      const entries = ['.env'];
      mockExistsSync.mockReturnValue(false);
      mockAppendFileSync.mockImplementation(() => {
        throw new Error('Permission denied');
      });

      expect(() => fileManager.updateGitignore(entries)).toThrow(CapyError);
      expect(() => fileManager.updateGitignore(entries)).toThrow('Failed to update .gitignore');
    });
  });

  describe('ensureCapyGitignore', () => {
    test('should add all capy entries in a single block', () => {
      const existingContent = 'node_modules\n';
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(existingContent);

      fileManager.ensureCapyGitignore();

      expect(mockAppendFileSync).toHaveBeenCalledWith(
        join(testRoot, '.gitignore'),
        '\n# Capy\n',
        'utf-8'
      );
      expect(mockAppendFileSync).toHaveBeenCalledWith(
        join(testRoot, '.gitignore'),
        '.env\n.capy\n.env.pre-capy.old\n.env.*.decrypted\n',
        'utf-8'
      );
    });
  });

  describe('backup operations', () => {
    test('should create backup for existing file', () => {
      const filePath = '/test/file.txt';
      const backupPath = '/test/file.txt.backup';
      const content = 'file content';

      mockExistsSync.mockImplementation((path) => path === filePath);
      mockReadFileSync.mockReturnValue(content);

      const result = (fileManager as any).createBackup(filePath);

      expect(result).toBe(backupPath);
      expect(mockWriteFileSync).toHaveBeenCalledWith(backupPath, content, { encoding: 'utf-8', mode: 0o600 });
    });

    test('should return null for non-existent file', () => {
      mockExistsSync.mockReturnValue(false);

      const result = (fileManager as any).createBackup('/test/nonexistent.txt');

      expect(result).toBeNull();
    });

    test('should restore backup successfully', () => {
      const backupPath = '/test/file.txt.backup';
      const originalPath = '/test/file.txt';
      const backupContent = 'backup content';

      mockExistsSync.mockImplementation((path) => path === backupPath);
      mockReadFileSync.mockReturnValue(backupContent);

      (fileManager as any).restoreBackup(backupPath, originalPath);

      expect(mockWriteFileSync).toHaveBeenCalledWith(originalPath, backupContent, 'utf-8');
      expect(mockUnlinkSync).toHaveBeenCalledWith(backupPath);
    });

    test('should handle backup restoration failure silently', () => {
      const backupPath = '/test/file.txt.backup';
      const originalPath = '/test/file.txt';

      mockReadFileSync.mockImplementation(() => {
        throw new Error('Read failed');
      });

      expect(() => (fileManager as any).restoreBackup(backupPath, originalPath)).not.toThrow();
    });

    test('should remove backup file', () => {
      const backupPath = '/test/file.txt.backup';
      mockExistsSync.mockReturnValue(true);

      (fileManager as any).removeBackup(backupPath);

      expect(mockUnlinkSync).toHaveBeenCalledWith(backupPath);
    });

    test('should handle backup removal failure silently', () => {
      const backupPath = '/test/file.txt.backup';
      mockExistsSync.mockReturnValue(true);
      mockUnlinkSync.mockImplementation(() => {
        throw new Error('Unlink failed');
      });

      expect(() => (fileManager as any).removeBackup(backupPath)).not.toThrow();
    });
  });

  describe('ensureDirectoryExists', () => {
    test('should create directory if it does not exist', () => {
      const dirPath = '/test/new/directory';
      mockExistsSync.mockReturnValue(false);

      (fileManager as any).ensureDirectoryExists(dirPath);

      expect(mockMkdirSync).toHaveBeenCalledWith(dirPath, { recursive: true });
    });

    test('should not create directory if it already exists', () => {
      const dirPath = '/test/existing/directory';
      mockExistsSync.mockReturnValue(true);

      (fileManager as any).ensureDirectoryExists(dirPath);

      expect(mockMkdirSync).not.toHaveBeenCalled();
    });
  });

  describe('backupPlaintextEnv', () => {
    test('should backup plaintext .env to .env.pre-capy.old with warning header', () => {
      const envContent = 'DB_URL=postgres://localhost\nAPI_KEY=sk_live_abc123\n';
      mockExistsSync.mockImplementation((p) => {
        if (String(p) === join(testRoot, '.env')) return true;
        return false;
      });
      mockReadFileSync.mockReturnValue(envContent);

      const result = fileManager.backupPlaintextEnv();

      expect(result).toBe(true);
      expect(mockWriteFileSync).toHaveBeenCalledWith(
        join(testRoot, '.env.pre-capy.old'),
        expect.stringContaining('From Capy'),
        { encoding: 'utf-8', mode: 0o600 }
      );
      // Verify the original content is included after the header
      const writtenContent = (mockWriteFileSync as any).mock.calls.find(
        (c: any[]) => String(c[0]).endsWith('.env.pre-capy.old')
      )?.[1] as string;
      expect(writtenContent).toContain('# DB_URL=postgres://localhost');
      expect(writtenContent).toContain('# API_KEY=sk_live_abc123');
      expect(writtenContent).toContain('unencrypted');
    });

    test('should add .env.pre-capy.old to .gitignore', () => {
      mockExistsSync.mockImplementation((p) => {
        if (String(p) === join(testRoot, '.env')) return true;
        return false;
      });
      mockReadFileSync.mockReturnValue('KEY=plaintext_value\n');

      fileManager.backupPlaintextEnv();

      expect(mockAppendFileSync).toHaveBeenCalledWith(
        join(testRoot, '.gitignore'),
        expect.stringContaining('.env.pre-capy.old'),
        'utf-8'
      );
    });

    test('should return false if .env does not exist', () => {
      mockExistsSync.mockReturnValue(false);

      const result = fileManager.backupPlaintextEnv();

      expect(result).toBe(false);
      expect(mockWriteFileSync).not.toHaveBeenCalled();
    });

    test('should return false if .env is already encrypted', () => {
      mockExistsSync.mockImplementation((p) => {
        if (String(p) === join(testRoot, '.env')) return true;
        return false;
      });
      mockReadFileSync.mockReturnValue(
        'DB_URL=capy:abc12:encrypted_data\nAPI_KEY=capy:def34:encrypted_data\n'
      );

      const result = fileManager.backupPlaintextEnv();

      expect(result).toBe(false);
      expect(mockWriteFileSync).not.toHaveBeenCalled();
    });

    test('should backup if mix of plaintext and encrypted values', () => {
      mockExistsSync.mockImplementation((p) => {
        if (String(p) === join(testRoot, '.env')) return true;
        return false;
      });
      mockReadFileSync.mockReturnValue(
        'DB_URL=capy:abc12:encrypted_data\nNEW_KEY=plaintext_value\n'
      );

      const result = fileManager.backupPlaintextEnv();

      expect(result).toBe(true);
    });

    test('should use custom path when provided', () => {
      const customPath = '/custom/.env';
      mockExistsSync.mockImplementation((p) => {
        if (String(p) === customPath) return true;
        return false;
      });
      mockReadFileSync.mockReturnValue('KEY=value\n');

      fileManager.backupPlaintextEnv(customPath);

      expect(mockWriteFileSync).toHaveBeenCalledWith(
        '/custom/.env.pre-capy.old',
        expect.stringContaining('# KEY=value'),
        { encoding: 'utf-8', mode: 0o600 }
      );
    });
  });
});