// GENERATED by scripts/sync-init-run-contract.ts; do not edit.
/**
 * CAP-652 v1 authentication rendezvous wire contract. No workflow authority,
 * platform imports, credential logging, or browser session material belongs here.
 * Consumer copies are generated by scripts/sync-init-run-contract.ts.
 */
export const INIT_RUN_VERSION = 1 as const;
export const INIT_RUN_PREAUTH_TTL_MS = 10 * 60 * 1000;
export const INIT_RUN_AUTHORIZED_TTL_MS = 2 * 60 * 60 * 1000;
export const INIT_RUN_TERMINAL_TTL_MS = 24 * 60 * 60 * 1000;
export const INIT_RUN_MAX_CLAIM_ATTEMPTS = 5;
export const INIT_RUN_AUTH_ENVELOPE_DOMAIN = 'capy:init-run:auth:v1';
export const INIT_RUN_STATES = ['pending_browser', 'browser_claimed', 'callback_ready', 'credential_ready', 'authorized', 'running', 'terminal', 'denied', 'expired'] as const;
export type InitRunPublicState = typeof INIT_RUN_STATES[number];

export const INIT_RUN_ERROR_CODES = [
  'INIT_RUN_INVALID', 'INIT_RUN_NOT_FOUND', 'INIT_RUN_CONFLICT', 'INIT_RUN_EXPIRED',
  'INIT_RUN_DENIED', 'INIT_RUN_CANCELLED', 'INIT_RUN_RATE_LIMITED', 'INIT_RUN_CONFIGURATION',
  'INIT_AUTH_PENDING', 'INIT_AUTH_FAILED', 'INIT_AUTH_SUBJECT_MISMATCH',
  'INIT_AUTH_ISSUANCE_LOST', 'INIT_CONNECTION_EXPIRED', 'INIT_PAGE_STATE_LOST',
  'INIT_BINDING_MISMATCH', 'INIT_DELIVERY_INDETERMINATE',
] as const;
export type InitRunErrorCode = typeof INIT_RUN_ERROR_CODES[number];

export type InitRunCreateRequest = Readonly<{
  v: 1; pkce_method: 'S256'; pkce_challenge: string; cli_pubkey: string;
  expected_user_id: string | null; service_origin: string; runtime_id: string;
  repository_fingerprint: string; machine_name: string;
}>;
export type InitRunCreateResponse = Readonly<{
  v: 1; run_id: string; run_secret: string; claim_code: string;
  entry_url: string; expires_at: string;
}>;
export type InitRunBinding = Readonly<{
  run_id: string; subject_user_id: string; service_origin: string;
  runtime_id: string; repository_fingerprint: string; cli_key_fingerprint: string;
}>;
export type InitRunTerminalReceipt = Readonly<{
  v: 1; run_id: string; receipt_id: string; status: 'succeeded' | 'cancelled' | 'failed' | 'expired';
  /** Structured canonical CLI error code; never an Error.message. */
  code: string | null; repository_verified: boolean; custody_verified: boolean;
  effects: 'none' | 'complete' | 'indeterminate'; completed_at: string;
}>;
export type InitRunStatusResponse = Readonly<{
  v: 1; run_id: string; status: InitRunPublicState;
  expected_user_id: string | null; subject_user_id: string | null;
  service_origin: string; runtime_id: string; repository_fingerprint: string;
  cli_key_fingerprint: string; machine_name: string; entry_url: string; expires_at: string;
  auth_epoch: number; authorization_pending: boolean;
  auth_error_code: InitRunErrorCode | null; first_connection_id: string | null;
  terminal_receipt: InitRunTerminalReceipt | null;
}>;
export type InitRunClaimRequest = Readonly<{ v: 1; decision: 'approve' | 'deny'; claim_code: string }>;
/** restart is only true after an explicit human action, never an automatic retry. */
export type InitRunAuthorizationRequest = Readonly<{ v: 1; restart: boolean }>;
export type InitRunAuthorizationResponse = Readonly<{
  v: 1; run_id: string; auth_epoch: number; authorization_url: string;
  callback_marker: string; expires_at: string;
}>;
export type InitRunCallbackRequest = Readonly<{
  v: 1; run_id: string; auth_epoch: number; callback_marker: string;
  code: string; state: string;
}>;
export type InitRunExchangeRequest = Readonly<{ v: 1; run_secret: string; pkce_verifier: string }>;
export type InitRunExchangeResponse =
  | Readonly<{ v: 1; status: 'pending'; retry_after_ms: number }>
  | Readonly<{ v: 1; status: 'complete'; binding: InitRunBinding; auth_epoch: number; credential_receipt: string; sealed_auth_result: string }>;
export type InitRunContinueRequest =
  | Readonly<{ v: 1; action: 'acknowledge'; run_secret: string; binding: InitRunBinding; credential_receipt: string }>
  | Readonly<{ v: 1; action: 'publish'; run_secret: string; binding: InitRunBinding; first_connection_id: string }>
  | Readonly<{ v: 1; action: 'terminal'; run_secret: string; binding: InitRunBinding; terminal_receipt: InitRunTerminalReceipt }>;
export type InitRunContinueResponse = InitRunStatusResponse;
export type InitRunLaunchPresentationRequest = Readonly<{ v: 1; claim_code_hash: string }>;
export type InitRunLaunchPresentationResponse = Readonly<{
  v: 1; run_id: string; expected_user_id: string; service_origin: string;
  runtime_id: string; repository_fingerprint: string; machine_name: string;
  entry_url: string; expires_at: string;
}>;

/** Existing /auth/exchange response, retaining its zero/one/multiple-org shapes. */
export type AuthResponseWire = Readonly<{
  token: Readonly<{ access_token: string | null; refresh_token: string; expires_in: number; scope?: 'user' }>;
  user: Readonly<{ id: string; email: string; first_name?: string | null; last_name?: string | null }>;
  organizations: readonly Readonly<{ id: string; workos_org_id: string; name: string; key_state: string }>[];
}>;
/** Only the CLI may open this encrypted plaintext; never expose it through GET. */
export type InitRunAuthResult = Readonly<{
  v: 1; binding: InitRunBinding; auth_epoch: number;
  response: AuthResponseWire; broker_access_token: string;
}>;

type RecordValue = Readonly<Record<string, unknown>>;
const record = (value: unknown): value is RecordValue => typeof value === 'object' && value !== null && !Array.isArray(value);
const text = (value: unknown, max = 256): value is string => typeof value === 'string' && value.length > 0 && value.length <= max && !/[\u0000-\u001f\u007f]/u.test(value);
const nullable = (value: unknown, check: (input: unknown) => boolean): boolean => value === null || check(value);
const integer = (value: unknown): value is number => typeof value === 'number' && Number.isSafeInteger(value) && value >= 0;
const keys = (value: RecordValue, required: readonly string[], optional: readonly string[] = []): boolean => required.every(key => Object.hasOwn(value, key)) && Object.keys(value).every(key => required.includes(key) || optional.includes(key));
const version = (value: RecordValue): boolean => value.v === INIT_RUN_VERSION;
const matches = (value: unknown, pattern: RegExp): value is string => typeof value === 'string' && pattern.test(value);
export const isInitRunId = (value: unknown): value is string => matches(value, /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u);
export const isInitRunFingerprint = (value: unknown): value is string => matches(value, /^sha256:[0-9a-f]{64}$/u);
export const normalizeRepositoryFingerprint = (value: string): string | null => isInitRunFingerprint(value) ? value : /^[0-9a-f]{64}$/u.test(value) ? `sha256:${value}` : null;
const userId = (value: unknown): value is string => matches(value, /^user_[A-Za-z0-9_\-]{1,123}$/u);
const secret = (value: unknown): value is string => matches(value, /^[A-Za-z0-9_-]{43}$/u);
const timestamp = (value: unknown): value is string => typeof value === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u.test(value) && Number.isFinite(Date.parse(value)) && new Date(value).toISOString() === value;
const errorCode = (value: unknown): value is InitRunErrorCode => typeof value === 'string' && INIT_RUN_ERROR_CODES.some(code => code === value);
/** Structural check only; callers must separately match an exact configured origin. */
export const isInitRunOrigin = (value: unknown): value is string => {
  if (!text(value, 2048)) return false;
  try {
    const url = new URL(value);
    return (url.protocol === 'https:' || url.protocol === 'http:') && url.origin === value && url.username === '' && url.password === '';
  } catch { return false; }
};
export const canonicalClaimCode = (value: unknown): string | null => {
  if (typeof value !== 'string') return null;
  const normalized = value.toUpperCase();
  return /^[0-9A-HJKMNP-TV-Z]{12}$/u.test(normalized) ? normalized
    : /^[0-9A-HJKMNP-TV-Z]{4}-[0-9A-HJKMNP-TV-Z]{4}-[0-9A-HJKMNP-TV-Z]{4}$/u.test(normalized) ? normalized.replaceAll('-', '') : null;
};
export const isInitRunEntryUrl = (value: unknown, runId: string): value is string => {
  if (!text(value, 4096)) return false;
  try {
    const url = new URL(value);
    return isInitRunOrigin(url.origin) && value === `${url.origin}/flow/init-wizard?run=${runId}`;
  } catch { return false; }
};
const authorizationUrl = (value: unknown): boolean => {
  if (!text(value, 16384)) return false;
  try {
    const url = new URL(value);
    return (url.protocol === 'https:' || url.protocol === 'http:') && url.username === '' && url.password === '' && url.hash === '';
  } catch { return false; }
};
const frozenFields = (value: RecordValue): boolean => isInitRunOrigin(value.service_origin) && isInitRunId(value.runtime_id) && isInitRunFingerprint(value.repository_fingerprint);

export const parseInitRunCreateRequest = (value: unknown): InitRunCreateRequest | null =>
  record(value) && keys(value, ['v', 'pkce_method', 'pkce_challenge', 'cli_pubkey', 'expected_user_id', 'service_origin', 'runtime_id', 'repository_fingerprint', 'machine_name']) && version(value)
  && value.pkce_method === 'S256' && secret(value.pkce_challenge)
  // Crypto consumers also validate the decoded point on P-256 before use.
  && matches(value.cli_pubkey, /^B[A-Za-z0-9+/]{86}=$/u)
  && nullable(value.expected_user_id, userId) && frozenFields(value) && text(value.machine_name, 128)
    ? value as InitRunCreateRequest : null;
export const parseInitRunCreateResponse = (value: unknown): InitRunCreateResponse | null =>
  record(value) && keys(value, ['v', 'run_id', 'run_secret', 'claim_code', 'entry_url', 'expires_at']) && version(value)
  && isInitRunId(value.run_id) && secret(value.run_secret) && matches(value.claim_code, /^[0-9A-HJKMNP-TV-Z]{4}-[0-9A-HJKMNP-TV-Z]{4}-[0-9A-HJKMNP-TV-Z]{4}$/u)
  && isInitRunEntryUrl(value.entry_url, value.run_id) && timestamp(value.expires_at) ? value as InitRunCreateResponse : null;
export const parseInitRunBinding = (value: unknown): InitRunBinding | null =>
  record(value) && keys(value, ['run_id', 'subject_user_id', 'service_origin', 'runtime_id', 'repository_fingerprint', 'cli_key_fingerprint'])
  && isInitRunId(value.run_id) && userId(value.subject_user_id) && frozenFields(value) && isInitRunFingerprint(value.cli_key_fingerprint) ? value as InitRunBinding : null;
export const sameInitRunBinding = (left: InitRunBinding, right: InitRunBinding): boolean =>
  left.run_id === right.run_id && left.subject_user_id === right.subject_user_id && left.service_origin === right.service_origin
  && left.runtime_id === right.runtime_id && left.repository_fingerprint === right.repository_fingerprint && left.cli_key_fingerprint === right.cli_key_fingerprint;
export const parseInitRunTerminalReceipt = (value: unknown): InitRunTerminalReceipt | null =>
  record(value) && keys(value, ['v', 'run_id', 'receipt_id', 'status', 'code', 'repository_verified', 'custody_verified', 'effects', 'completed_at']) && version(value)
  && isInitRunId(value.run_id) && isInitRunId(value.receipt_id) && ['succeeded', 'cancelled', 'failed', 'expired'].includes(String(value.status))
  && nullable(value.code, code => matches(code, /^[A-Z][A-Z0-9_]{0,127}$/u)) && typeof value.repository_verified === 'boolean' && typeof value.custody_verified === 'boolean'
  && ['none', 'complete', 'indeterminate'].includes(String(value.effects)) && timestamp(value.completed_at)
  && (value.status !== 'succeeded' || (value.code === null && value.repository_verified && value.effects === 'complete'))
  && (value.status === 'succeeded' || value.code !== null)
    ? value as InitRunTerminalReceipt : null;
export const parseInitRunStatusResponse = (value: unknown): InitRunStatusResponse | null =>
  record(value) && keys(value, ['v', 'run_id', 'status', 'expected_user_id', 'subject_user_id', 'service_origin', 'runtime_id', 'repository_fingerprint', 'cli_key_fingerprint', 'machine_name', 'entry_url', 'expires_at', 'auth_epoch', 'authorization_pending', 'auth_error_code', 'first_connection_id', 'terminal_receipt']) && version(value)
  && isInitRunId(value.run_id) && INIT_RUN_STATES.some(state => state === value.status) && nullable(value.expected_user_id, userId) && nullable(value.subject_user_id, userId)
  && frozenFields(value) && isInitRunFingerprint(value.cli_key_fingerprint) && text(value.machine_name, 128) && isInitRunEntryUrl(value.entry_url, value.run_id) && timestamp(value.expires_at)
  && integer(value.auth_epoch) && typeof value.authorization_pending === 'boolean' && nullable(value.auth_error_code, errorCode)
  && nullable(value.first_connection_id, isInitRunId) && nullable(value.terminal_receipt, receipt => parseInitRunTerminalReceipt(receipt) !== null)
  && (value.terminal_receipt === null || (value.terminal_receipt as InitRunTerminalReceipt).run_id === value.run_id)
    ? value as InitRunStatusResponse : null;
export const parseInitRunClaimRequest = (value: unknown): InitRunClaimRequest | null =>
  record(value) && keys(value, ['v', 'decision', 'claim_code']) && version(value) && (value.decision === 'approve' || value.decision === 'deny') && canonicalClaimCode(value.claim_code) !== null ? value as InitRunClaimRequest : null;
export const parseInitRunAuthorizationRequest = (value: unknown): InitRunAuthorizationRequest | null =>
  record(value) && keys(value, ['v', 'restart']) && version(value) && typeof value.restart === 'boolean' ? value as InitRunAuthorizationRequest : null;
export const parseInitRunAuthorizationResponse = (value: unknown): InitRunAuthorizationResponse | null =>
  record(value) && keys(value, ['v', 'run_id', 'auth_epoch', 'authorization_url', 'callback_marker', 'expires_at']) && version(value)
  && isInitRunId(value.run_id) && integer(value.auth_epoch) && value.auth_epoch > 0 && authorizationUrl(value.authorization_url) && secret(value.callback_marker) && timestamp(value.expires_at) ? value as InitRunAuthorizationResponse : null;
export const parseInitRunCallbackRequest = (value: unknown): InitRunCallbackRequest | null =>
  record(value) && keys(value, ['v', 'run_id', 'auth_epoch', 'callback_marker', 'code', 'state']) && version(value)
  && isInitRunId(value.run_id) && integer(value.auth_epoch) && value.auth_epoch > 0 && secret(value.callback_marker) && text(value.code, 8192) && secret(value.state) ? value as InitRunCallbackRequest : null;
export const parseInitRunExchangeRequest = (value: unknown): InitRunExchangeRequest | null =>
  record(value) && keys(value, ['v', 'run_secret', 'pkce_verifier']) && version(value) && secret(value.run_secret) && matches(value.pkce_verifier, /^[A-Za-z0-9._~-]{43,128}$/u) ? value as InitRunExchangeRequest : null;
export const parseInitRunExchangeResponse = (value: unknown): InitRunExchangeResponse | null => {
  if (!record(value) || !version(value)) return null;
  if (value.status === 'pending') return keys(value, ['v', 'status', 'retry_after_ms']) && integer(value.retry_after_ms) && value.retry_after_ms >= 100 && value.retry_after_ms <= 30000 ? value as InitRunExchangeResponse : null;
  return value.status === 'complete' && keys(value, ['v', 'status', 'binding', 'auth_epoch', 'credential_receipt', 'sealed_auth_result']) && parseInitRunBinding(value.binding) !== null
    && integer(value.auth_epoch) && value.auth_epoch > 0 && isInitRunFingerprint(value.credential_receipt) && text(value.sealed_auth_result, 262144) ? value as InitRunExchangeResponse : null;
};
export const parseInitRunContinueRequest = (value: unknown): InitRunContinueRequest | null => {
  if (!record(value) || !version(value) || !secret(value.run_secret) || !parseInitRunBinding(value.binding)) return null;
  const common = ['v', 'action', 'run_secret', 'binding'] as const;
  if (value.action === 'acknowledge') return keys(value, [...common, 'credential_receipt']) && isInitRunFingerprint(value.credential_receipt) ? value as InitRunContinueRequest : null;
  if (value.action === 'publish') return keys(value, [...common, 'first_connection_id']) && isInitRunId(value.first_connection_id) ? value as InitRunContinueRequest : null;
  if (value.action === 'terminal') return keys(value, [...common, 'terminal_receipt']) && parseInitRunTerminalReceipt(value.terminal_receipt) && (value.terminal_receipt as InitRunTerminalReceipt).run_id === (value.binding as InitRunBinding).run_id ? value as InitRunContinueRequest : null;
  return null;
};
export const parseInitRunContinueResponse = parseInitRunStatusResponse;
export const parseInitRunLaunchPresentationRequest = (value: unknown): InitRunLaunchPresentationRequest | null =>
  record(value) && keys(value, ['v', 'claim_code_hash']) && version(value) && isInitRunFingerprint(value.claim_code_hash) ? value as InitRunLaunchPresentationRequest : null;
export const parseInitRunLaunchPresentationResponse = (value: unknown): InitRunLaunchPresentationResponse | null =>
  record(value) && keys(value, ['v', 'run_id', 'expected_user_id', 'service_origin', 'runtime_id', 'repository_fingerprint', 'machine_name', 'entry_url', 'expires_at']) && version(value)
  && isInitRunId(value.run_id) && userId(value.expected_user_id) && frozenFields(value) && text(value.machine_name, 128) && isInitRunEntryUrl(value.entry_url, value.run_id) && timestamp(value.expires_at) ? value as InitRunLaunchPresentationResponse : null;
export const parseAuthResponseWire = (value: unknown): AuthResponseWire | null => {
  if (!record(value) || !keys(value, ['token', 'user', 'organizations']) || !record(value.token) || !record(value.user) || !Array.isArray(value.organizations)) return null;
  const token = value.token;
  const user = value.user;
  return keys(token, ['access_token', 'refresh_token', 'expires_in'], ['scope']) && nullable(token.access_token, input => text(input, 65536)) && text(token.refresh_token, 65536) && integer(token.expires_in)
    && (token.scope === undefined || token.scope === 'user') && keys(user, ['id', 'email'], ['first_name', 'last_name']) && userId(user.id) && text(user.email, 320)
    && [user.first_name, user.last_name].every(name => name === undefined || name === null || (typeof name === 'string' && name.length <= 256))
    && value.organizations.every(org => record(org) && keys(org, ['id', 'workos_org_id', 'name', 'key_state']) && text(org.id) && text(org.workos_org_id) && text(org.name) && text(org.key_state))
      ? value as AuthResponseWire : null;
};
export const parseInitRunAuthResult = (value: unknown): InitRunAuthResult | null =>
  record(value) && keys(value, ['v', 'binding', 'auth_epoch', 'response', 'broker_access_token']) && version(value)
  && parseInitRunBinding(value.binding) !== null && integer(value.auth_epoch) && value.auth_epoch > 0 && parseAuthResponseWire(value.response) !== null && text(value.broker_access_token, 65536)
  && (value.binding as InitRunBinding).subject_user_id === (value.response as AuthResponseWire).user.id ? value as InitRunAuthResult : null;

/** The encrypted broker carries presentation bytes; the CLI owns their meaning. */
export type InitWizardScreen = 'init-wizard' | 'create-organization' | 'device-key';
type InitWizardCorrelation = Readonly<{ v: 1; flow: 'init-wizard'; binding: InitRunBinding; sequence: number; attempt_id: string }>;
export type InitWizardFrame<T> = InitWizardCorrelation & (
  | Readonly<{ kind: 'view' | 'progress' | 'ceremony'; screen: InitWizardScreen; data: T; next_connection_id: string }>
  | Readonly<{ kind: 'final'; screen: InitWizardScreen; data: T; terminal_receipt: InitRunTerminalReceipt }>
);
export type InitWizardAnswer = InitWizardCorrelation & (
  | Readonly<{ kind: 'answer'; answer: Readonly<Record<string, unknown>> }>
  | Readonly<{ kind: 'cancel' | 'progress-ack' }>
);
const correlation = (value: RecordValue): boolean => version(value) && value.flow === 'init-wizard' && parseInitRunBinding(value.binding) !== null
  && integer(value.sequence) && matches(value.attempt_id, /^[A-Za-z0-9_-]{1,128}$/u);
const correlationKeys = ['v', 'flow', 'binding', 'sequence', 'attempt_id'] as const;
/** Data validation is screen-specific and injected by each presentation consumer. */
export function parseInitWizardFrame<T>(value: unknown, parseData: (screen: InitWizardScreen, value: unknown) => T | null): InitWizardFrame<T> | null {
  if (!record(value) || !correlation(value) || !['init-wizard', 'create-organization', 'device-key'].includes(String(value.screen))) return null;
  const screen = value.screen as InitWizardScreen;
  const data = parseData(screen, value.data);
  if (data === null) return null;
  if (value.kind === 'final') {
    const receipt = parseInitRunTerminalReceipt(value.terminal_receipt);
    return keys(value, [...correlationKeys, 'kind', 'screen', 'data', 'terminal_receipt']) && receipt !== null && receipt.run_id === (value.binding as InitRunBinding).run_id
      ? { ...value, data } as InitWizardFrame<T> : null;
  }
  return ['view', 'progress', 'ceremony'].includes(String(value.kind)) && keys(value, [...correlationKeys, 'kind', 'screen', 'data', 'next_connection_id']) && isInitRunId(value.next_connection_id)
    && (value.kind !== 'ceremony' || screen === 'device-key') ? { ...value, data } as InitWizardFrame<T> : null;
}
export function parseInitWizardAnswer(value: unknown): InitWizardAnswer | null {
  if (!record(value) || !correlation(value)) return null;
  if (value.kind === 'answer') return keys(value, [...correlationKeys, 'kind', 'answer']) && record(value.answer) ? value as InitWizardAnswer : null;
  return (value.kind === 'cancel' || value.kind === 'progress-ack') && keys(value, [...correlationKeys, 'kind']) ? value as InitWizardAnswer : null;
}
